#!/bin/bash

# Location of the home template ( configs, etc )
USER_HOME=${USER_HOME:-${HOME}/ws/home}

build() {
    buildah --name codeui from debian:bookworm

    buildah copy codeui sbin/ /sbin
    buildah run codeui  /sbin/setup-deb all

    # Normally home is mounted. A vnc password must be set for VNC to
    # work - provisioning the home is a separate operation.
    buildah copy --chown build codeui  ${USER_HOME} /home/build

    buildah copy codeui ../../../rootfs/etc/ /etc

}

push() {
    # About 2GB
    buildah commit codeui git.h.webinf.info/costin/dev/ui:latest
    buildah push git.h.webinf.info/costin/dev/ui:latest
}

pull() {
  buildah from --name codeui git.h.webinf.info/costin/dev/ui:latest
}
USER=costin
USERID=1002

run() {
  # Temp - share the home\
  buildah run --network host \
    -e USER=${USER} \
    -e USERID=${USERID} \
    -v $HOME:/home/${USER} \
    -v $(pwd)/sbin/init:/sbin/init \
    -t codeui /sbin/init "$@"
}

"$@"
