#!/bin/bash

#buildah copy codeui sbin/* /sbin

#buildah from --name codeui git.h.webinf.info/costin/dev/ui:latest

# Temp - share the home\
buildah run --network host \
  -v $HOME:/root \
  -v $(pwd)/sbin/init:/sbin/init \
  -t codeui /sbin/init "$@"

podman run -it --rm --network host -v /home/costin16:/home/build \
 git.h.webinf.info/costin/dev/ui:latest /sbin/init bash