#!/bin/bash

USER=costin
USERID=1002

#DOPT="-it --rm"
DOPT="-d --restart always"


IMAGE=git.h.webinf.info/costin/dev/ui:latest 

podman pull ${IMAGE}
docker rm -f codeui

podman run ${DOPT} \
   --name codeui --network host \
    -e USER=${USER} \
    -e USERID=${USERID} \
    -v /home/costin16:/home/${USER} \
    -v $(pwd)/sbin/init-pod:/sbin/init-pod \
     ${IMAGE} \
    /sbin/init-pod start
