#!/bin/sh


# Default target for recovery in docker
install() {
  alpine_add_common
  alpine_add_base

  apk add firefox code
  rm -rf /tmp/*
}


# Useful packages for a host. 
alpine_add_common() {

  # Will add busybox-mdev as baseline
  apk add   busybox-suid busybox-binsh
    
  apk add ca-certificates-bundle
    
  # Alternative: dropbear dropbear-openrc
  apk add openssh openssh-keygen openssh-sftp-server

  apk add curl rsync

  # from karios - not sure we need it
  apk add  findutils findmnt \
    htop haveged \
    iproute2 \
    sudo strace util-linux \
    socat tcpdump iputils procps hdparm
  
  # init with a single process. Can reap even if not running as PID1.
  apk add tini

  # arch-chroot works great with other OSes
  apk add arch-install-scripts

}


# Base users, groups, packages.
alpine_add_base() {
  [ -f /etc/resolv.conf ] ||  echo "nameserver 1.1.1.1" > /etc/resolv.conf

  addgroup -g 1000 build
  addgroup -g 1001 admin

  # -H: don't create home
  # -D: no pass
  # -S - system user - nologin (i.e. /bin/login and passwd access will be disabled - ssh ok)
  # -g - 'gecos' or name
  adduser -G build -g "Builder" build -u 1000 -D -s /bin/sh -h /home/build
  adduser -G admin -g "Admin" admin -u 1001 -D -s /bin/sh -h /home/admin

  # Add the user to the sudoers group
  addgroup admin wheel
  addgroup admin kvm

  addgroup build users # otherwise swayunlock fails, /etc/shaddow permissions
  addgroup build video
  addgroup build audio
  addgroup build tty
  addgroup build input
  addgroup build kvm
  addgroup build wheel


  # Disable IPv6 for now - seems to be broken in some cases. Can be enabled in rootfs.
  #echo "net.ipv6.conf.all.disable_ipv6 = 1" >>/etc/sysctl.conf

  chown root /root

  # Enable a system user to use login:
  # Remove password: -d
  # passwd -u build
}




"$@"
