#!/usr/bin/env bash
#
# run_qemu.sh — Boot the prebuilt initos test image set with QEMU using EFI and
# TPM2 emulation.
#
# Usage:
#   ./scripts/build.sh
#   ./tests/run_qemu.sh
#   nix build path:$PWD
#   ./tests/run_qemu.sh --nix-result result
#
# Expects artifacts generated by scripts/build.sh:
# - target/test_efi as /dev/vda - file=fat,media=disk
# - target/qemu/state.ext4 as /dev/vdb - to verify decryption.
# 
# No longer adding the ext4 or vfat to the gpt image - faster to
# use separate images, not impacting the boot sequence.
#
# The boot sequence is:
# - EFI - based on the minimal rust EFI
#   - custom bzImage and cmdline configuring qemu init script
#   - the script will mount 9p with extra images and test scripts
#   - the ext4 will be loaded with LABEL=STATE.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJECT_ROOT}"

src=${src:-${PROJECT_ROOT}}
out=${out:-${src}/target}

PATH=${src}/prebuilt/bin:${src}/sidecar/bin:/sbin:/usr/sbin:$PATH

# The EFI dir - will be exported as vfat in qemu, no need to create an img.
ESP_DIR="${out}/test_efi"
INITOS_INIT=${INITOS_INIT:-/opt/initos/bin/initos-init-qemu}

set_out() {
    out="${1:?Usage: set_out <out-dir>}"
    ESP_DIR="${out}/test_efi"
}

stage_nix_artifacts() {
    local nix_result="${1:-${NIX_RESULT:-result}}"
    local rootfs_img="${nix_result}/img/initos.erofs"

    if [[ ! -f "${rootfs_img}" ]]; then
        echo "Missing Nix rootfs image: ${rootfs_img}" >&2
        exit 1
    fi
    if ! command -v mcopy >/dev/null 2>&1; then
        echo "mcopy is required to stage Nix boot artifacts" >&2
        exit 1
    fi

    set_out "${NIX_QEMU_OUT:-${src}/target/nix-qemu}"

    rm -rf "${ESP_DIR}" "${out}/disks" "${out}/qemu/state.ext4"
    mkdir -p "${ESP_DIR}" "${out}/disks/state/img" "${out}/test"

    cp "${rootfs_img}" "${out}/disks/state/img/initos.erofs"
    for f in "${nix_result}"/img/*.sig; do
        [ -f "$f" ] && cp "$f" "${out}/disks/state/img/"
    done

    echo "=== Staging Nix boot images ==="
    for variant in boot-limine-unsigned boot-initos-signed boot-limine-signed; do
        local img_path="${nix_result}/img/${variant}.img"
        if [[ -f "${img_path}" ]]; then
            mkdir -p "${out}/disks/${variant}"
            mcopy -i "${img_path}" -s ::EFI "${out}/disks/${variant}/" || true
            mcopy -i "${img_path}" -s ::keys "${out}/disks/${variant}/" || true
        else
            echo "Warning: Nix boot image not found: ${img_path}" >&2
        fi
    done

    build_qemu_state
}

nix() {
    stage_nix_artifacts "${1:-${NIX_RESULT:-result}}"
    RESET_QEMU_STATE_FROM_ARTIFACTS=0 test
}

build_qemu_state() {
    local rootfs_img="${out}/disks/state/img/initos.erofs"
    local genimage_dir="${out}/test"
    local data_img="state.ext4"
    local img_size_bytes img_size_mb state_size_mb

    img_size_bytes=$(stat -c%s "${rootfs_img}")
    img_size_mb=$(( (img_size_bytes + 1048575) / 1048576 ))
    state_size_mb=$(( img_size_mb + 32 + 64 ))
    echo "STATE_SIZE_MB: ${state_size_mb} (IMG: ${rootfs_img})"

    mkdir -p "${genimage_dir}"
    dd if=/dev/zero of="${genimage_dir}/${data_img}" bs=1M count="${state_size_mb}" status=none

    mkfs.ext4 -q -F -b 4096 \
        -O inline_data,extents,uninit_bg,dir_index,has_journal,verity,encrypt \
        -L "STATE" -d "${out}/disks/state" \
        "${genimage_dir}/${data_img}"
}


require_artifacts() {
    local missing=0

    if [[ ! -f "${out}/qemu/state.ext4" ]]; then
        echo "Missing state.ext4 disk at ${out}/qemu/state.ext4" >&2
        missing=1
    fi

    for variant in boot-limine-unsigned boot-initos-signed boot-limine-signed; do
        if [[ ! -f "${out}/disks/img/${variant}.vfat" ]]; then
            echo "Missing signed boot image: ${out}/disks/img/${variant}.vfat" >&2
            missing=1
        fi
    done

    if [[ "$missing" -ne 0 ]]; then
        echo "Run ./scripts/build.sh before ./tests/run_qemu.sh." >&2
        exit 1
    fi
}

run() {
    local timeout_s="${1:-${TIMEOUT:-30}}"
    # 4. Run QEMU
    OVMF="prebuilt/OVMF.fd"
    local log_file="${LOG_FILE:-${out}/qemu_efi.log}"
    rm -f "$log_file"

    QEMU_ARGS=(
        -drive "file=fat:rw:${ESP_DIR},media=disk,format=raw"
        -drive "file=${out}/qemu/state.ext4,format=raw,if=none,id=initos_state"
        -device "nvme,drive=initos_state,serial=initos-state"
    )

    # Same as: -bios $OVMF
    QEMU_ARGS+=(-drive "if=pflash,readonly=on,format=raw,file=${OVMF}")
    OVMF_VARS="$(dirname "${OVMF}")/OVMF_VARS.fd"
    QEMU_ARGS+=(-drive "if=pflash,format=raw,file=${OVMF_VARS}")

    TPM_DIR="${QEMU_TPM_DIR:-${out}/tmp/mytpm1}"
    if [[ "${RESET_TPM:-1}" != 0 ]]; then
        rm -rf "${TPM_DIR}"
    fi
    mkdir -p "${TPM_DIR}"
    rm -f "${TPM_DIR}/swtpm-sock"
    swtpm socket --tpmstate dir="${TPM_DIR}" --ctrl type=unixio,path="${TPM_DIR}/swtpm-sock" --tpm2 &
    local swtpm_pid=$!
    tpm="-chardev socket,id=chrtpm,path=${TPM_DIR}/swtpm-sock -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0"
    QEMU_ARGS+=(${tpm})

    QEMU_ARGS+=(
        -fsdev "local,security_model=mapped,id=fsdev0,path=${out}/qemu"
        -device "virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=src"
        -device "virtio-serial-pci"
        -chardev "socket,id=mesh,path=${out}/qemu/mesh.sock,server=on,wait=off"
        -device "virtserialport,chardev=mesh,name=org.ssh-mesh.control"
    )

	# -display none or -nographic ?
    QEMU_ARGS+=(
        -m 512M
        -smp 2
        -no-reboot
        -nographic
        -nodefaults
    )
    if [[ -w /dev/kvm ]]; then
        QEMU_ARGS+=(-enable-kvm -cpu host)
    else
        echo "WARNING: KVM not available, using emulation (slower)"
        QEMU_ARGS+=(-cpu qemu64)
    fi

    if [ -n "${INITOS_DEBUG:-}" ]; then
        QEMU_ARGS+=(
        -chardev stdio,mux=on,id=char0
        -serial chardev:char0
        -device virtconsole,chardev=char0
        -monitor chardev:char0
        )
        qemu-system-x86_64 "${QEMU_ARGS[@]}" | tee "$log_file"
    else
        echo "=== Starting QEMU (timeout ${timeout_s}s) ==="
        set +e
        timeout --foreground "${timeout_s}s" qemu-system-x86_64 "${QEMU_ARGS[@]}"             -chardev "file,mux=on,id=char0,path=${log_file}"             -serial chardev:char0             -device virtconsole,chardev=char0             -no-reboot
   		rc=$?
        kill "${swtpm_pid}" 2>/dev/null || true
        wait "${swtpm_pid}" 2>/dev/null || true
        set -e
		if [[ $rc -eq 124 ]]; then
			echo ""
			echo "=== QEMU timed out after ${timeout_s}s ==="
		elif [[ $rc -ne 0 ]]; then
			echo ""
			echo "=== QEMU exited with status ${rc} ==="
			exit "$rc"
		fi

    fi
}

test_unsigned_negative() {
    echo "=== Running Negative Test (Unsigned bootloader) ==="
    rm -rf "${ESP_DIR}"
    mkdir -p "${ESP_DIR}"
    
    mcopy -i "${out}/disks/img/boot-limine-unsigned.vfat" -s ::EFI "${ESP_DIR}/" || true
    mcopy -i "${out}/disks/img/boot-limine-unsigned.vfat" -s ::keys "${ESP_DIR}/" || true

    # Write QEMU command line config
    cat > "${ESP_DIR}/EFI/BOOT/config" <<EOF
rdinit=/init loglevel=9 console=hvc0 INITOS_INIT=${INITOS_INIT} rw iommu=relaxed net.ifnames=0 panic=5
EOF

    local log_file="${out}/qemu_efi_unsigned.log"
    LOG_FILE="${log_file}" run 6

    echo "=== Analyzing Unsigned Boot (Expected to Fail) ==="
    if grep -q "Linux version" "${log_file}" || grep -q "InitOS EFI Loader" "${log_file}"; then
        echo "❌ FAILURE: Unsigned bootloader or kernel booted successfully under Secure Boot!"
        exit 1
    else
        echo "✅ SUCCESS: Unsigned bootloader was blocked by Secure Boot!"
    fi
}

test_limine_signed() {
    echo "=== Running Signed Limine Direct Boot Test ==="
    rm -rf "${ESP_DIR}"
    mkdir -p "${ESP_DIR}"
    local signed_timeout_s="${SIGNED_TIMEOUT:-${TIMEOUT:-30}}"
    
    # We want to re-run sign.sh build_boot_limine_signed with the correct INITOS_CMDLINE for testing console=hvc0
    local keys="${src}/prebuilt/testdata/uefi-keys"
    local pub_key
    pub_key=$(tr -d '\r\n' < "${keys}/image_key.pub.b64")
    INITOS_CMDLINE="rdinit=/init loglevel=9 console=hvc0 INITOS_INIT=${INITOS_INIT} rw iommu=relaxed net.ifnames=0 panic=5" \
        "${src}/sidecar/bin/sign.sh" build_boot_limine_signed "${out}/artifacts/boot" "${out}/disks/tmp" "${keys}" "${pub_key}"

    mcopy -i "${out}/disks/tmp/img/boot-limine-signed.vfat" -s ::EFI "${ESP_DIR}/" || true
    mcopy -i "${out}/disks/tmp/img/boot-limine-signed.vfat" -s ::keys "${ESP_DIR}/" || true

    local log_file="${out}/qemu_efi_limine_signed.log"
    LOG_FILE="${log_file}" run "${signed_timeout_s}"

    echo "=== Analyzing Signed Limine Boot ==="
    
    if grep -q "Run .* as init process" "${log_file}" && \
        grep -q "initos: image signature verified OK" "${log_file}" && \
        grep -q "=== ALL TESTS COMPLETE ===" "${log_file}"; then
        echo "✅ SUCCESS: Signed Limine booted and completed all tests!"
    else
        echo "❌ FAILURE: Signed Limine boot failed or did not complete tests."
        exit 1
    fi
}

test_initos_signed() {
    echo "=== Running Signed InitOS Custom Loader Boot Test ==="
    rm -rf "${ESP_DIR}"
    mkdir -p "${ESP_DIR}"

    local keys="${src}/prebuilt/testdata/uefi-keys"
    local pub_key
    pub_key=$(tr -d '\r\n' < "${keys}/image_key.pub.b64")
    local tpm_dir="${out}/tmp/initos-signed-tpm"
    local signed_timeout_s="${SIGNED_TIMEOUT:-${TIMEOUT:-30}}"
    rm -rf "${tpm_dir}"

    INITOS_CMDLINE="rdinit=/init loglevel=9 console=hvc0 INITOS_INIT=${INITOS_INIT} INITOS_QEMU_PHASE=setup rw iommu=relaxed net.ifnames=0 panic=5" \
        "${src}/sidecar/bin/sign.sh" build_boot_initos_signed "${out}/artifacts/boot" "${out}/disks/tmp" "${keys}" "${pub_key}"

    mcopy -i "${out}/disks/tmp/img/boot-initos-signed.vfat" -s ::EFI "${ESP_DIR}/" || true
    mcopy -i "${out}/disks/tmp/img/boot-initos-signed.vfat" -s ::keys "${ESP_DIR}/" || true

    local setup_log_file="${out}/qemu_efi_initos_signed_setup.log"
    QEMU_TPM_DIR="${tpm_dir}" RESET_TPM=1 LOG_FILE="${setup_log_file}" run "${signed_timeout_s}"

    echo "=== Analyzing Signed InitOS TPM Setup Boot ==="
    if grep -q "=== INITRD TPM UNLOCK SETUP OK ===" "${setup_log_file}"; then
        echo "✅ SUCCESS: Signed InitOS setup boot created TPM-backed /z/c state!"
    else
        echo "❌ FAILURE: Signed InitOS setup boot did not create TPM-backed /z/c state."
        exit 1
    fi

    rm -rf "${ESP_DIR}"
    mkdir -p "${ESP_DIR}"

    INITOS_CMDLINE="rdinit=/init loglevel=9 console=hvc0 INITOS_INIT=${INITOS_INIT} INITOS_QEMU_PHASE=verify rw iommu=relaxed net.ifnames=0 panic=5" \
        "${src}/sidecar/bin/sign.sh" build_boot_initos_signed "${out}/artifacts/boot" "${out}/disks/tmp" "${keys}" "${pub_key}"

    mcopy -i "${out}/disks/tmp/img/boot-initos-signed.vfat" -s ::EFI "${ESP_DIR}/" || true
    mcopy -i "${out}/disks/tmp/img/boot-initos-signed.vfat" -s ::keys "${ESP_DIR}/" || true

    local log_file="${out}/qemu_efi_initos_signed.log"
    QEMU_TPM_DIR="${tpm_dir}" RESET_TPM=0 LOG_FILE="${log_file}" run "${signed_timeout_s}"

    echo "=== Analyzing Signed InitOS Boot ==="

    if grep -q "console=hvc0" "${log_file}" && \
        grep -q "INITOS_PUB_KEY=${pub_key}" "${log_file}" && \
        (grep -q "✅ RSA Signature VERIFIED for config" "${log_file}" || grep -q "✅ CONFIG VERIFIED OK" "${log_file}") && \
        (grep -q "✅ RSA Signature VERIFIED for kernel" "${log_file}" || grep -q "✅ KERNEL VERIFIED OK" "${log_file}") && \
        grep -q "initos: image signature verified OK" "${log_file}" && \
        grep -q "initos: unlocked /z/c using TPM" "${log_file}" && \
        grep -q "initos: verifying image /z/img/firmware.erofs" "${log_file}" && \
        grep -q "initos: verifying image /z/img/modules-.*\\.erofs" "${log_file}" && \
        grep -q "initos: mounting /z/img/firmware.erofs at /sysroot/mnt/firmware" "${log_file}" && \
        grep -q "initos: mounting /z/img/modules-.*\\.erofs at /sysroot/mnt/modules/.*" "${log_file}" && \
        grep -q "initos: binding /sysroot/mnt/firmware to /sysroot/usr/lib/firmware" "${log_file}" && \
        grep -q "initos: binding /sysroot/mnt/modules to /sysroot/usr/lib/modules" "${log_file}" && \
        grep -q "initos: mounting proc at /sysroot/proc" "${log_file}" && \
        grep -q "initos: mounting sysfs at /sysroot/sys" "${log_file}" && \
        grep -q "initos: mounting devtmpfs at /sysroot/dev" "${log_file}" && \
        grep -q "=== INITRD TPM UNLOCK OK ===" "${log_file}" && \
        grep -q "=== INITRD ROOTFS FIRMWARE BIND OK ===" "${log_file}" && \
        grep -q "=== INITRD ROOTFS MODULES BIND OK ===" "${log_file}" && \
        grep -q "=== INITRD ROOTFS HOME BIND OK ===" "${log_file}" && \
        (grep -q "=== INITRD ROOTFS ROOT BIND OK ===" "${log_file}" || grep -q "=== INITRD ROOTFS ROOT BIND SKIP ===" "${log_file}") && \
        grep -q "=== INITRD ROOTFS NIX BIND OK ===" "${log_file}" && \
        grep -q "=== ALL TESTS COMPLETE ===" "${log_file}"; then
        echo "✅ SUCCESS: Signed InitOS booted, unlocked /z/c in initrd, verified module/firmware mounts, and completed all tests!"
    else
        echo "❌ FAILURE: Signed InitOS boot verification failed."
        exit 1
    fi
}
test() {
    if [[ "${RESET_QEMU_STATE_FROM_ARTIFACTS:-1}" != 0 ]]; then
        "${src}/scripts/build.sh" build_qemu_state
    fi
    require_artifacts
    test_unsigned_negative
    test_limine_signed
    test_initos_signed
}

if [[ "${1:-}" == "--nix-result" ]]; then
    shift
    nix "${1:-${NIX_RESULT:-result}}"
    exit 0
fi

if [[ $# -gt 0 ]]; then
    for cmd in "$@"; do
        $cmd
    done
    exit 0
fi

test    
