#!/usr/bin/env bash
#
# run_qemu.sh — Boot the prebuilt initos test image set with QEMU using EFI and
# TPM2 emulation.
#
# Usage:
#   ./scripts/build.sh
#   ./tests/run_qemu.sh
#
# Expects artifacts generated by scripts/build.sh:
# - target/test_efi as /dev/vda - file=fat,media=disk
# - target/test/state.ext4 as /dev/vdb - to verify decryption.
# 
# No longer adding the ext4 or vfat to the gpt image - faster to
# use separate images, not impacting the boot sequence.
#
# The boot sequence is:
# - EFI - based on the minimal rust EFI
#   - custom bzImage and cmdline configuring qemu init script
#   - the script will mount 9p with extra images and test scripts
#   - the ext4 will be loaded with LABEL=STATE.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJECT_ROOT}"

# Auto-enter nix-shell if QEMU isn't in PATH (see scripts/shell.nix)
if [ -z "${IN_NIX_SHELL:-}" ] && [ -z "${INITOS_NIX_DONE:-}" ] \
    && ! command -v qemu-system-x86_64 >/dev/null 2>&1 \
    && command -v nix-shell >/dev/null 2>&1; then
    if [ -f "${PROJECT_ROOT}/scripts/shell.nix" ]; then
        echo "run_qemu.sh: entering nix-shell..."
        export INITOS_NIX_DONE=1
        exec nix-shell "${PROJECT_ROOT}/scripts/shell.nix" --run "bash $0 $*"
    fi
fi


SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJECT_ROOT}"

src=${src:-${PROJECT_ROOT}}
out=${out:-${src}/target}

# The EFI dir - will be exported as vfat in qemu, no need to create an img.
ESP_DIR="${out}/test_efi"
INITOS_INIT=${INITOS_INIT:-/opt/initos/bin/initos-init-qemu}

require_artifacts() {
    local missing=0
    local f

    local sec_dir="${src}/prebuilt/testdata/uefi-keys"
    local KEY_ID="unknown"
    if [[ -f "${sec_dir}/db.crt" ]]; then
        echo "Found db.crt at ${sec_dir}/db.crt"
        KEY_ID=$(openssl x509 -in "${sec_dir}/db.crt" -pubkey -noout | openssl rsa -pubin -outform DER 2>/dev/null | openssl dgst -sha256 | sed 's/.*= //' | cut -c 1-16)
        echo "Computed KEY_ID: '${KEY_ID}'"
    else
        echo "Did not find db.crt at ${sec_dir}/db.crt. PWD is $(pwd), src is ${src}"
    fi

    for f in \
        "${ESP_DIR}/EFI/BOOT/BOOTX64.EFI" \
        "${ESP_DIR}/EFI/BOOT/bzImage" \
        "${ESP_DIR}/EFI/BOOT/config" \
        "${ESP_DIR}/EFI/BOOT/initrd.img" \
        "${ESP_DIR}/EFI/BOOT/${KEY_ID}.sig" \
        "${ESP_DIR}/EFI/BOOT/${KEY_ID}.kernel.sig" \
        "${ESP_DIR}/EFI/BOOT/${KEY_ID}.initrd.sig" \
        "${out}/test/state.ext4"; do
        if [[ ! -f "$f" ]]; then
            echo "Missing QEMU artifact: $f" >&2
            missing=1
        fi
    done

    if [[ "$missing" -ne 0 ]]; then
        echo "Run ./scripts/build.sh before ./tests/run_qemu.sh." >&2
        exit 1
    fi
}

run() {
    # 4. Run QEMU
    OVMF="prebuilt/OVMF.fd"
    LOG_FILE="target/qemu_efi.log"
    rm -f "$LOG_FILE"

    QEMU_ARGS=(
        -drive "file=fat:rw:${ESP_DIR},media=disk,format=raw"
        #-drive "file=${out}/test/disk.img,format=raw,if=none,id=initos_img"
        #-device "nvme,drive=initos_img,serial=initos-img"
        -drive "file=${out}/test/state.ext4,format=raw,if=none,id=initos_state"
        -device "nvme,drive=initos_state,serial=initos-state"
    )

    # Same as: -bios $OVMF
    QEMU_ARGS+=(-drive "if=pflash,readonly=on,format=raw,file=${OVMF}")
    OVMF_VARS="$(dirname "${OVMF}")/OVMF_VARS.fd"
    QEMU_ARGS+=(-drive "if=pflash,format=raw,file=${OVMF_VARS}")

    TPM_DIR="${out}/tmp/mytpm1"
    rm -rf "${TPM_DIR}"
    mkdir -p "${TPM_DIR}"
    swtpm socket --tpmstate dir="${TPM_DIR}" --ctrl type=unixio,path="${TPM_DIR}/swtpm-sock" --tpm2 &
    tpm="-chardev socket,id=chrtpm,path=${TPM_DIR}/swtpm-sock -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0"
    QEMU_ARGS+=(${tpm})

    QEMU_ARGS+=(
        -fsdev "local,security_model=mapped,id=fsdev0,path=${out}/test"
        -device "virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=src"
        -device "virtio-serial-pci"
        -chardev "socket,id=mesh,path=${out}/test/mesh.sock,server=on,wait=off"
        -device "virtserialport,chardev=mesh,name=org.ssh-mesh.control"
    )

	# -display none or -nographic ?
    QEMU_ARGS+=(
        -m 512M
        -smp 2
        -no-reboot
        -nographic
        -nodefaults
    )
    if [[ -w /dev/kvm ]]; then
        QEMU_ARGS+=(-enable-kvm -cpu host)
    else
        echo "WARNING: KVM not available, using emulation (slower)"
        QEMU_ARGS+=(-cpu qemu64)
    fi

    # Capture EFI serial output and kernel hvc0 output through one muxed log.
    if [ -n "${INITOS_DEBUG:-}" ]; then
        QEMU_ARGS+=(
        -chardev stdio,mux=on,id=char0
        -serial chardev:char0
        -device virtconsole,chardev=char0
        -monitor chardev:char0
        )
        qemu-system-x86_64 "${QEMU_ARGS[@]}" | tee "$LOG_FILE"
    else
        local timeout_s=${TIMEOUT:-30}
        echo "=== Starting QEMU (timeout ${timeout_s}s) ==="
        set +e
        timeout --foreground "${timeout_s}s" qemu-system-x86_64 "${QEMU_ARGS[@]}" \
            -chardev "file,mux=on,id=char0,path=$LOG_FILE" \
            -serial chardev:char0 \
            -device virtconsole,chardev=char0 \
            -no-reboot
   		rc=$?
        set -e
		if [[ $rc -eq 124 ]]; then
			echo ""
			echo "=== QEMU timed out after ${timeout_s}s; analyzing captured log ==="
		elif [[ $rc -ne 0 ]]; then
			echo ""
			echo "=== QEMU exited with status ${rc} ==="
			exit "$rc"
		fi

    fi
}

test() {
    require_artifacts
    run
    analyze
}

analyze() {
    echo ""
    echo "=== Analyzing Results ==="
    cat "$LOG_FILE"

    if grep -q "Command line:.*console=hvc0.*" "$LOG_FILE"; then
        echo "✅ SUCCESS: Config file read correctly!"
    else
        echo "❌ FAILURE: Config file was not read correctly or command line mismatch."
        exit 1
    fi

    if grep -q "✅ RSA Signature VERIFIED for config" "$LOG_FILE"; then
        echo "✅ SUCCESS: Config RSA Signature verified!"
    else
        echo "❌ FAILURE: Config RSA Signature verification failed or did not run."
        exit 1
    fi

    if grep -q "✅ RSA Signature VERIFIED for kernel" "$LOG_FILE"; then
        echo "✅ SUCCESS: Kernel RSA Signature verified!"
    else
        echo "❌ FAILURE: Kernel RSA Signature verification failed or did not run."
        exit 1
    fi

    if grep -q "✅ CONFIG VERIFIED OK" "$LOG_FILE" ; then
        echo "✅ SUCCESS: Full verification passed!"
    else
        echo "❌ FAILURE: Full verification failed."
        exit 1
    fi

    echo "=== Checking Kernel Activity ==="
    if grep -i -q "Linux version" "$LOG_FILE" || grep -q "Run .* as init process" "$LOG_FILE"; then
        echo "✅ SUCCESS: Kernel started!"
    elif grep -q "Jumping to handover" "$LOG_FILE"; then
        echo "⚠️  Handover executed but no kernel output. (Check serial console settings)"
    else
        echo "❌ FAILURE: Kernel did not start or no output captured."
    fi

    if grep -q "INITOS:" "$LOG_FILE"; then
        echo "✅ SUCCESS: initos script is running!"
    elif grep -i -q "Unable to mount root fs" "$LOG_FILE"; then
        echo "⚠️  Kernel started but panicked finding init. (Progress!)"
    fi
}

if [[ $# -gt 0 ]]; then
    for cmd in "$@"; do
        $cmd
    done
    exit 0
fi

test    
