#!/usr/bin/env bash
#
# run_qemu.sh — Boot the prebuilt initos test image set with QEMU using EFI and
# TPM2 emulation.
#
# Usage:
#   ./scripts/build.sh
#   ./tests/run_qemu.sh
#   nix build path:$PWD
#   ./tests/run_qemu.sh --nix-result result
#
# Expects artifacts generated by scripts/build.sh:
# - target/test_efi as /dev/vda - file=fat,media=disk
# - target/test/state.ext4 as /dev/vdb - to verify decryption.
# 
# No longer adding the ext4 or vfat to the gpt image - faster to
# use separate images, not impacting the boot sequence.
#
# The boot sequence is:
# - EFI - based on the minimal rust EFI
#   - custom bzImage and cmdline configuring qemu init script
#   - the script will mount 9p with extra images and test scripts
#   - the ext4 will be loaded with LABEL=STATE.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
cd "${PROJECT_ROOT}"

src=${src:-${PROJECT_ROOT}}
out=${out:-${src}/target}

PATH=${src}/prebuilt/bin:${src}/sidecar/bin:/sbin:/usr/sbin:$PATH

# The EFI dir - will be exported as vfat in qemu, no need to create an img.
ESP_DIR="${out}/test_efi"
INITOS_INIT=${INITOS_INIT:-/opt/initos/bin/initos-init-qemu}

set_out() {
    out="${1:?Usage: set_out <out-dir>}"
    ESP_DIR="${out}/test_efi"
}

stage_nix_artifacts() {
    local nix_result="${1:-${NIX_RESULT:-result}}"
    local boot_img="${nix_result}/img/boot-initos-signed.img"
    local rootfs_img="${nix_result}/img/initos.erofs"

    if [[ ! -f "${boot_img}" ]]; then
        echo "Missing Nix boot image: ${boot_img}" >&2
        exit 1
    fi
    if [[ ! -f "${rootfs_img}" ]]; then
        echo "Missing Nix rootfs image: ${rootfs_img}" >&2
        exit 1
    fi
    if ! command -v mcopy >/dev/null 2>&1; then
        echo "mcopy is required to stage Nix boot artifacts" >&2
        exit 1
    fi

    set_out "${NIX_QEMU_OUT:-${src}/target/nix-qemu}"

    rm -rf "${ESP_DIR}" "${out}/disks/state" "${out}/test/state.ext4"
    mkdir -p "${ESP_DIR}" "${out}/disks/state/img" "${out}/test"

    echo "=== Staging Nix artifacts from ${nix_result} into ${out} ==="
    mcopy -i "${boot_img}" -s ::EFI "${ESP_DIR}/"
    cp "${rootfs_img}" "${out}/disks/state/img/initos.erofs"

    cat > "${ESP_DIR}/EFI/BOOT/config" <<EOF
rdinit=/init loglevel=9 console=hvc0 INITOS_INIT=${INITOS_INIT} rw iommu=relaxed net.ifnames=0 panic=5
EOF

    "${src}/scripts/sign.sh" efi "${src}/prebuilt/testdata/uefi-keys" "${ESP_DIR}/"
    build_qemu_state
}

nix() {
    stage_nix_artifacts "${1:-${NIX_RESULT:-result}}"
    test
}

build_qemu_state() {
    local rootfs_img="${out}/disks/state/img/initos.erofs"
    local genimage_dir="${out}/test"
    local data_img="state.ext4"
    local img_size_bytes img_size_mb state_size_mb

    img_size_bytes=$(stat -c%s "${rootfs_img}")
    img_size_mb=$(( (img_size_bytes + 1048575) / 1048576 ))
    state_size_mb=$(( img_size_mb + 32 + 64 ))
    echo "STATE_SIZE_MB: ${state_size_mb} (IMG: ${rootfs_img})"

    mkdir -p "${genimage_dir}"
    dd if=/dev/zero of="${genimage_dir}/${data_img}" bs=1M count="${state_size_mb}" status=none

    mkfs.ext4 -q -F -b 4096 \
        -O inline_data,extents,uninit_bg,dir_index,has_journal,verity,encrypt \
        -L "STATE" -d "${out}/disks/state" \
        "${genimage_dir}/${data_img}"
}

require_artifacts() {
    local missing=0
    local f

    local sec_dir="${src}/prebuilt/testdata/uefi-keys"
    local KEY_ID="unknown"
    if [[ -f "${sec_dir}/db.crt" ]]; then
        echo "Found db.crt at ${sec_dir}/db.crt"
        KEY_ID=$(openssl x509 -in "${sec_dir}/db.crt" -pubkey -noout | openssl rsa -pubin -outform DER 2>/dev/null | openssl dgst -sha256 | sed 's/.*= //' | cut -c 1-16)
        echo "Computed KEY_ID: '${KEY_ID}'"
    else
        echo "Did not find db.crt at ${sec_dir}/db.crt. PWD is $(pwd), src is ${src}"
    fi

    for f in \
        "${ESP_DIR}/EFI/BOOT/BOOTX64.EFI" \
        "${ESP_DIR}/EFI/BOOT/bzImage" \
        "${ESP_DIR}/EFI/BOOT/config" \
        "${ESP_DIR}/EFI/BOOT/initrd.img" \
        "${ESP_DIR}/EFI/BOOT/${KEY_ID}.sig" \
        "${ESP_DIR}/EFI/BOOT/${KEY_ID}.kernel.sig" \
        "${ESP_DIR}/EFI/BOOT/${KEY_ID}.initrd.sig" \
        "${out}/test/state.ext4"; do
        if [[ ! -f "$f" ]]; then
            echo "Missing QEMU artifact: $f" >&2
            missing=1
        fi
    done

    if [[ "$missing" -ne 0 ]]; then
        echo "Run ./scripts/build.sh before ./tests/run_qemu.sh." >&2
        exit 1
    fi
}

run() {
    # 4. Run QEMU
    OVMF="prebuilt/OVMF.fd"
    local log_file="${LOG_FILE:-${out}/qemu_efi.log}"
    rm -f "$log_file"

    QEMU_ARGS=(
        -drive "file=fat:rw:${ESP_DIR},media=disk,format=raw"
        #-drive "file=${out}/test/disk.img,format=raw,if=none,id=initos_img"
        #-device "nvme,drive=initos_img,serial=initos-img"
        -drive "file=${out}/test/state.ext4,format=raw,if=none,id=initos_state"
        -device "nvme,drive=initos_state,serial=initos-state"
    )

    # Same as: -bios $OVMF
    QEMU_ARGS+=(-drive "if=pflash,readonly=on,format=raw,file=${OVMF}")
    OVMF_VARS="$(dirname "${OVMF}")/OVMF_VARS.fd"
    QEMU_ARGS+=(-drive "if=pflash,format=raw,file=${OVMF_VARS}")

    TPM_DIR="${out}/tmp/mytpm1"
    rm -rf "${TPM_DIR}"
    mkdir -p "${TPM_DIR}"
    swtpm socket --tpmstate dir="${TPM_DIR}" --ctrl type=unixio,path="${TPM_DIR}/swtpm-sock" --tpm2 &
    tpm="-chardev socket,id=chrtpm,path=${TPM_DIR}/swtpm-sock -tpmdev emulator,id=tpm0,chardev=chrtpm -device tpm-tis,tpmdev=tpm0"
    QEMU_ARGS+=(${tpm})

    QEMU_ARGS+=(
        -fsdev "local,security_model=mapped,id=fsdev0,path=${out}/test"
        -device "virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=src"
        -device "virtio-serial-pci"
        -chardev "socket,id=mesh,path=${out}/test/mesh.sock,server=on,wait=off"
        -device "virtserialport,chardev=mesh,name=org.ssh-mesh.control"
    )

	# -display none or -nographic ?
    QEMU_ARGS+=(
        -m 512M
        -smp 2
        -no-reboot
        -nographic
        -nodefaults
    )
    if [[ -w /dev/kvm ]]; then
        QEMU_ARGS+=(-enable-kvm -cpu host)
    else
        echo "WARNING: KVM not available, using emulation (slower)"
        QEMU_ARGS+=(-cpu qemu64)
    fi

    # Capture EFI serial output and kernel hvc0 output through one muxed log.
    if [ -n "${INITOS_DEBUG:-}" ]; then
        QEMU_ARGS+=(
        -chardev stdio,mux=on,id=char0
        -serial chardev:char0
        -device virtconsole,chardev=char0
        -monitor chardev:char0
        )
        qemu-system-x86_64 "${QEMU_ARGS[@]}" | tee "$log_file"
    else
        local timeout_s=${TIMEOUT:-30}
        echo "=== Starting QEMU (timeout ${timeout_s}s) ==="
        set +e
        timeout --foreground "${timeout_s}s" qemu-system-x86_64 "${QEMU_ARGS[@]}" \
            -chardev "file,mux=on,id=char0,path=${log_file}" \
            -serial chardev:char0 \
            -device virtconsole,chardev=char0 \
            -no-reboot
   		rc=$?
        set -e
		if [[ $rc -eq 124 ]]; then
			echo ""
			echo "=== QEMU timed out after ${timeout_s}s; analyzing captured log ==="
		elif [[ $rc -ne 0 ]]; then
			echo ""
			echo "=== QEMU exited with status ${rc} ==="
			exit "$rc"
		fi

    fi
}

test() {
    require_artifacts
    run
    analyze
}

analyze() {
    local log_file="${LOG_FILE:-${out}/qemu_efi.log}"
    echo ""
    echo "=== Analyzing Results ==="
    cat "$log_file"

    if grep -q "Command line:.*console=hvc0.*" "$log_file"; then
        echo "✅ SUCCESS: Config file read correctly!"
    else
        echo "❌ FAILURE: Config file was not read correctly or command line mismatch."
        exit 1
    fi

    if grep -q "✅ RSA Signature VERIFIED for config" "$log_file"; then
        echo "✅ SUCCESS: Config RSA Signature verified!"
    else
        echo "❌ FAILURE: Config RSA Signature verification failed or did not run."
        exit 1
    fi

    if grep -q "✅ RSA Signature VERIFIED for kernel" "$log_file"; then
        echo "✅ SUCCESS: Kernel RSA Signature verified!"
    else
        echo "❌ FAILURE: Kernel RSA Signature verification failed or did not run."
        exit 1
    fi

    if grep -q "✅ CONFIG VERIFIED OK" "$log_file" ; then
        echo "✅ SUCCESS: Full verification passed!"
    else
        echo "❌ FAILURE: Full verification failed."
        exit 1
    fi

    echo "=== Checking Kernel Activity ==="
    if grep -i -q "Linux version" "$log_file" || grep -q "Run .* as init process" "$log_file"; then
        echo "✅ SUCCESS: Kernel started!"
    elif grep -q "Jumping to handover" "$log_file"; then
        echo "⚠️  Handover executed but no kernel output. (Check serial console settings)"
    else
        echo "❌ FAILURE: Kernel did not start or no output captured."
    fi

    if grep -q "INITOS:" "$log_file"; then
        echo "✅ SUCCESS: initos script is running!"
    elif grep -i -q "Unable to mount root fs" "$log_file"; then
        echo "⚠️  Kernel started but panicked finding init. (Progress!)"
    fi
}

if [[ "${1:-}" == "--nix-result" ]]; then
    shift
    nix "${1:-${NIX_RESULT:-result}}"
    exit 0
fi

if [[ $# -gt 0 ]]; then
    for cmd in "$@"; do
        $cmd
    done
    exit 0
fi

test    
