#!/bin/bash

# Location of the home template ( configs, etc )
USER_HOME=${USER_HOME:-${HOME}/ws/home}

POD=${POD:-adev}

build() {
    buildah --name ${POD} from alpine:edge || true


    buildah copy ${POD} sbin/ /sbin
    buildah run ${POD}  /sbin/setup-ui install

    # Normally home is mounted. A vnc password must be set for VNC to
    # work - provisioning the home is a separate operation.
    buildah copy --chown build ${POD}  ${USER_HOME} /home/build

}
IMAGE=git.h.webinf.info/costin/dev/adev:latest
run() {
  buildah commit ${POD} ${IMAGE}

  podman run --network host \
    -v /home/build:/home/build \
    -v $(pwd)/sbin/init-pod:/sbin/init-pod \
    -it --rm ${IMAGE} /sbin/init-pod "$@"
}

"$@"
