timeout: 2
serial: yes
graphics: no
verbose: yes
editor_enabled: yes

# EFI boot dir using limine boot loader
# Mainly for testing/experiments - use the minimal efi for
# secure boot, simpler and safer than limine process.

# nomodeset console=efifb earlyprintk=efi 

/Boot
  protocol: linux
  cmdline: console=tty1 net.ifnames=0 panic=5 loglevel=6   
  path: boot():/EFI/BOOT/bzImage
  module_path: boot():/EFI/BOOT/initrd.img
# Normal boot - not verified. Will use img/initos.erofs as first root.
 
/Boot-USB
  protocol: linux
  cmdline: INITOS_DATA=USTATE console=tty1 net.ifnames=0 panic=5 loglevel=6   
  path: boot():/EFI/BOOT/bzImage
  module_path: boot():/EFI/BOOT/initrd.img
# Normal boot - not verified. Will use img/initos.erofs as first root.

/Initos-EFI
    protocol: efi
    path: boot():/EFI/BOOT/initos.efi
