timeout: 2
serial: yes
graphics: no
verbose: yes
editor_enabled: yes

# EFI boot dir using limine boot loader
# Mainly for testing/experiments - use the minimal efi for
# secure boot, simpler and safer than limine process.

# nomodeset console=efifb earlyprintk=efi 

/Boot
  protocol: linux
  cmdline: INITOS_INIT=/opt/initos/bin/initos-init-dev console=ttyS0,115200 console=tty1 net.ifnames=0 panic=5 loglevel=6   
  path: boot():/EFI/BOOT/bzImage
  module_path: boot():/EFI/BOOT/initrd.img
# Normal boot - not verified. Will use img/initos.erofs as first root.
 

/Boot-ROOTA
  protocol: linux
  path: boot():/EFI/BOOT/bzImage
  cmdline: root=PARTLABEL=STATE init=/opt/initos/bin/initos-init-dev console=tty1 imomem=relaxed net.ifnames=0 panic=5 loglevel=6 
# Direct boot to the STATE partition - expected to contain /opt/initos 
# This skips the initrd.img - easier to debug/adjust the scripts.

/Boot-ROOTA-sh
  protocol: linux
  path: boot():/EFI/BOOT/bzImage
  cmdline: root=PARTLABEL=STATE init=/opt/busybox/bin/sh console=tty1 imomem=relaxed net.ifnames=0 panic=5 loglevel=6 
# Shell on the STATE disk, assuming it is properly populated.

/Boot-USB-sh
  protocol: linux
  path: boot():/EFI/BOOT/bzImage
  cmdline: root=PARTLABEL=USTATE init=/opt/initos/bin/initios-int-dev console=tty1 imomem=relaxed net.ifnames=0 panic=5 loglevel=6 
