timeout: 2
serial: yes
graphics: no
verbose: yes
editor_enabled: yes

/Boot-ROOTA
  protocol: linux
  path: boot():/EFI/LINUX/bzImage
  cmdline: root=PARTLABEL=STATE console=tty1 imomem=relaxed net.ifnames=0 panic=5 loglevel=6 

/Boot-ROOTA-sh
  protocol: linux
  path: boot():/EFI/LINUX/bzImage
  cmdline: root=PARTLABEL=ROOT-A init=/bin/sh console=tty1 imomem=relaxed net.ifnames=0 panic=5 loglevel=6 

/Boot-Sidecar
  protocol: linux
  path: boot():/EFI/LINUX/bzImage
  cmdline: root=PARTLABEL=ROOT-B console=tty1 imomem=relaxed net.ifnames=0 panic=5 loglevel=6 

/Boot-Sidecar-sh
  protocol: linux
  path: boot():/EFI/LINUX/bzImage
  cmdline: root=PARTLABEL=ROOT-B init=/bin/sh console=tty1 imomem=relaxed net.ifnames=0 panic=5 loglevel=6 


/Boot-USB-sh
  protocol: linux
  path: boot():/EFI/LINUX/bzImage
  cmdline: root=PARTLABEL=DATA-U init=/bin/sh console=tty1 imomem=relaxed net.ifnames=0 panic=5 loglevel=6 
