#!/bin/sh

# Init script for the recovery image. Runs as PID 1.
. /sbin/init-common.sh

echo "Recovery shell - exec /sbin/openrc-init or /sbin/init for using recovery as a rootfs"

busybox ash

# - from initrd
# - in a VM
# - direct from kernel
# - in a pod

