#!/bin/sh

SRCDIR=${SRCDIR:-/ws/initos}

### Alpine specific packages for the recovery image.
# Not using "--no-cache" - and installing one by one.
# When running in docker, this will be cached to /var/cache/apk/[INDEX] - which is a mounted dir.
# /etc/apk/cache will cache the actual files

install_recovery() {
  cp -a ${SRCDIR}/recovery/sbin/* /sbin/
  cp -a ${SRCDIR}/recovery/etc/* /etc/
#  cp -a ${SRCDIR}/recovery/home /
#  cp -a ${SRCDIR}/recovery/root /
#  chown -R root /root
  install
}

install() {
  alpine_add_common
  alpine_add_base
  alpine_add_recovery

  #Only on edge
  #apk add openrc-init

  # Add the config files
  cp -a -f ${SRCDIR}/recovery/etc/* /etc/

  (cd /etc/init.d && ln -s agetty agetty.tty1)
  (cd /etc/init.d && ln -s agetty agetty.tty2)
  # Using busybox init
  #rc-update add agetty.tty1 boot
  #rc-update add agetty.tty2 default
#  rc-update add agetty.ttyS0 boot
#  rc-update add agetty.hvc0 boot

  rc-update add devfs sysinit
  rc-update add dmesg sysinit

  # Those 3 can be used instead of udev
  # This is the busybox mdev
  # apk add busybox-mdev-openrc
  # busybox-mdev busybox-mdev-openrc
  #apk add mdev-conf
  #rc-update add hwdrivers sysinit
  #rc-update add mdev sysinit

  # apk add --quiet mdevd mdevd-openrc
  #rc-update add hwdrivers sysinit
  #rc-update add mdevd-init sysinit
  #rc-update add mdevd sysinit

  # modloop will load after dev-mount, read KOPT_modoop and KOPT_modloop_verify
  # checks using openssl using public key under /etc/apk/keys/*.pub
  # Modules are loaded as overlay (so more can be added)
  #rc-update del modloop sysinit
  rc-update add udev sysinit
  rc-update add udev-trigger sysinit
  rc-update add udev-settle sysinit
  rc-update add cgroups sysinit

  #  rc-update add connman boot
  rc-update add acpid boot
  rc-update add ntpd boot
  rc-update add wpa_supplicant boot
  rc-update add modules boot
  rc-update add sysctl boot
  rc-update add hostname boot
  rc-update add bootmisc boot
  rc-update add syslog boot
  rc-update add hwclock boot
  rc-update add networking boot

  rc-update add dropbear default
  rc-update add udev-postmount default


  rc-update add mount-ro shutdown
  rc-update add killprocs shutdown
  #rc-update add savecache shutdown

  rc-update --update
  # Temp - debug only
  # TODO: in initrd, patch /etc/shadow to remove password instead
  # would be useful with all cloud images...
  #passwd -d root

}

alpine_add_common() {
    echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
    apk -U --no-progress update

    #apk list -I

    #apk add alpine-base # Installs openrc
    apk add ifupdown-ng libcap2  openrc  alpine-conf  alpine-release  busybox-openrc  busybox-suid

    apk add eudev eudev-hwids udev-init-scripts udev-init-scripts-openrc
    apk del busybox-mdev-openrc mdev-conf || true
    #setup-devd udev

    # Will add busybox-mdev as baseline
    apk add openrc
    apk add alpine-conf
    apk add   busybox-suid busybox-binsh
    apk add iw ifupdown-ng ifupdown-ng-wifi
    apk add ca-certificates-bundle
    # Using it for few things - minisign can probably be used instead.
    # 765k bin + 5M lib
    apk add openssl
    apk add ssl_client

}

# If starting with an alpine distro, add the packages we need.
alpine_add_recovery() {

  apk add rsync

  apk add busybox-openrc

  apk add dropbear dropbear-openrc
  apk add openssh-keygen
  # fsverity CLI
  #apk add fsverity-utils

  # To build the UKI
  apk add binutils

  apk add tpm2-tools tpm2-tss-tcti-device tpm2-tss-tcti-cmd tpm2-tss

  apk add lsblk

  # sgdisk gptfdisk
  apk add  parted

  apk add cryptsetup uuidgen

  # clevis adds bash, jose, cacklib
  # apk add clevis

  apk add bridge

  # 400k
  apk add minisign

  apk add btrfs-progs

  apk add mkinitfs
  echo 'disable_trigger=yes' >> /etc/mkinitfs/mkinitfs.conf


  # 104 packages, 1.1G under lib/firmware
  # /lib/modules, /boot/vmlinuz-lts (plus config, system map)
  apk add gummiboot

  apk add efibootmgr

  apk add squashfs-tools

  # To decompress firmware in zstd format (debian doesn't load it)
  apk add zstd

  # troubleshooting
  #apk add pcituils

  apk add efi-mkuki
  apk add efi-mkkeys
  apk add sbsigntool

  apk add openssh-sftp-server

  apk add curl

  apk add dmidecode

  # fsck, etc
  apk add dosfstools

  apk add wpa_supplicant wpa_supplicant-openrc


  # from karios - not sure we need it
  apk add  findutils findmnt \
    htop haveged \
    iproute2 \
    irqbalance \
    lm-sensors \
    lsscsi \
    lvm2 \
    mdadm \
    smartmontools \
    sudo strace util-linux bridge \
    socat tcpdump iputils procps

  # About 7M extra
  apk add cloud-hypervisor virtiofsd

  # podman instead of docker: no daemon. Adds ~70M

  # Deps: crun container, gpg, etc
  # /var/lib/containers must be a tmpfs or btrfs (not overlayfs)
  # requires fuse-overlayfs
  apk add podman podman-openrc podman-docker fuse-overlayfs
  # podman-tui

  # arch-chroot works great with other OSes
  apk add arch-install-scripts

  # similar to ujail and others - no server.
  # nsjail can listen on a port and start container on connection
  # supports macvlan
  # can act as an init (restart on exit)
  # logs of deps (abseil, protobuf)
  #apk add nsjail

  # init with a single process. Can reap even if not running as PID1.
  apk add tini

  #apk add secureboot-hook

  # Others that may be useful but not required:

  # apk add kmod lddtree kmod-libs
  #  apk add iproute2 tcpdump procps

  # For OCI interaction
  apk add crane
  # Can also encrypt/decrypt - 3.7M + 2M for keygen
  #apk add age

  #e2fsprogs

  # apk add lvm2

}

# Base users, groups, packages.
alpine_add_base() {
  [ -f /etc/resolv.conf ] ||  echo "nameserver 1.1.1.1" > /etc/resolv.conf


  mkdir -p /boot/efi
  mkdir -p /lib/modules
  mkdir -p /lib/firmware
  mkdir -p /mnt/usb

  addgroup -g 1000 build
  addgroup -g 1001 admin
  #addgroup -g 1002 tss

  adduser -G build -g "Builder" build -u 1000 -D -s /bin/sh -h /home/build
  adduser -G admin -g "Admin" admin -u 1001 -D -s /bin/sh -h /home/admin
  #adduser -G tss -g "Builder" tss -u 1002

  # Add the user to the sudoers group
  addgroup admin wheel
  addgroup admin kvm
  addgroup build users # otherwise swayunlock fails, /etc/shaddow permissions
  addgroup build video
  addgroup build audio

  # Disable IPv6 for now - seems to be broken in some cases. Can be enabled in rootfs.
  #echo "net.ipv6.conf.all.disable_ipv6 = 1" >>/etc/sysctl.conf

  chown root /root

# -H: don't create home
# -D: no pass
# -S - system user - nologin (i.e. /bin/login and passwd access will be disabled - ssh ok)
# -g - 'gecos' or name
  # Enable a system user to use login:
  #passwd -u build
  # Remove password: -d

}

ui() {
  apk add bash bash-completion

  apk add firefox-esr
  #  apk add mesa-dri-gallium
  setup-desktop sway
  apk add kitty
  apk add rofi-wayland rofi-pass rofi-top
  apk add chromium

  apk add seatd


  #apk add i3wm dbus-x11
  #apk add tint2 rofi alttab i3status
  #apk add xorg-server
  #apk add xinit
#  apk add xset
#  apk add xrandr
#  apk add xmodmap
#  apk add xinput
#  apk add xhost
#  apk add xkill
}

$*
