#!/bin/sh

# Install script for Initos. It assumes it was directly booted or chroot/container in the recovery image, where all
# tools are available.
# 
# wipe_disk  requires the /dev/DISK to be available - bind mount if running in a container.
# 
# 

# Where to store the luks key during setup (some commands require a file)
SECRETS=/run/secrets/luks

# Unlike ignition (which runs in Dracut initramfs), this script runs on a full alpine OS
# with networking and the usual tools. It is not designed to wipe the disk or be declarative -
# just to configure the minimum required for the machine to boot with the signed UKI image
# and have the recovery image available.

# It does have ability to create an EFI, LUKS and btrfs filesystem on an empty disk, but
# will require explicit user action to do so on a non-empty disk. If EFI/LUKS and btrfs
# are present - it will add itself to EFI and to a btrfs subvolume.

# It can also download an OCI rootfs and save it to a subvolume, and use it on next
# boot.

# Each function should do a simple operation and be kept very simple and easy to be
# modified to fit specific needs - without having to add complex config and logic to
# hide what is actually happening.

# Will wipe a disk a create the partitions needed for initos.
# This should be called explicitly by the user - it will normally not be done automatically.
# In practice we need ~100M on the EFI, and some btrfs volume.
#
wipe_disk() {
  disk_dev=$1
  suffix=$2

  # use 100% to fill the disk. This is total, EFI and root.
  # It is possible to later use the rest of the disk for LUKS, LVM or other work partitions.

  # List partitions with parted
  partitions=$(parted --script --machine -- "${disk_dev}" unit s print)

  parted --script --machine -- "${disk_dev}" mklabel gpt


  parted "$disk_dev" mkpart ESP fat32 1 2048
  parted "$disk_dev" set 1 boot on

#  parted "$disk_dev" mkpart primary ext4 2048 4096
#  parted "$disk_dev" name 2 "recovery"
#
#  parted "$disk_dev" mkpart primary ext4 4096 4596
#  parted "$disk_dev" name 3 "recovery_verity"

  # Create the Linux partition
  parted "$disk_dev" mkpart primary ext4 2048 8GiB
  parted "$disk_dev" name 2 "LUKS"

  partprobe $disk_dev

  mkfs.vfat ${disk_dev}${suffix}1 -n BOOT
}

mkLUKS() {
  local disk_dev=$1
  local key=$2

  # Linux LUKS partition type is 8309
  # -v -c aes-xts-plain64 -s 512 --hash sha512 --pbkdf pbkdf2 \
  #   --iter-time 1000 --use-random
  echo -n "${KEY}" | cryptsetup luksFormat --type luks2 ${disk_dev} -

  echo -n "${KEY}" | cryptsetup luksOpen ${disk_dev} c -

  mkfs.btrfs /dev/mapper/c
  # Doesn't really matter, visible after encyption unlock.
  btrfs filesystem label /dev/mapper/c "ROOT"

  # TODO: encrypt the PASSPRASE with the root public key, save it to USB for recovery.
  # TODO: if tpm present, save it to TPM
}

xinit() {
    btrfs subvol create /x/vol
    btrfs subvol create /x/@home
    btrfs subvol create /x/@cache
    btrfs subvol create /x/@log
    btrfs subvol create /x/@recovery
    mkdir /x/@recovery/rw

    # Subvolume for large images (no copy on write)
    mkdir -p /x/vol/images
    chattr +C /x/vol/images

}

# Create a LUKS encrypted filesystem, with a btrtf volume on top.
# The password is random and saved to TPM and in 'escrow' using the /boot/root.pem public key
# (that means the mesh owner can recover the passoword)
mkcrypt() {
  local disk_dev=$1

  init_pass

  save_tpm_full ${KEY}

  echo "Consider adding a recovery key"

  # Linux LUKS partition type is 8309
  # -v -c aes-xts-plain64 -s 512 --hash sha512 --pbkdf pbkdf2 \
  #   --iter-time 1000 --use-random
  echo -n "${KEY}" | cryptsetup luksFormat --type luks2 ${disk_dev} -

  echo -n "${KEY}" | cryptsetup luksOpen ${disk_dev} c -

  mkfs.btrfs /dev/mapper/c
  # Doesn't really matter, visible after encyption unlock.
  btrfs filesystem label /dev/mapper/c "ROOT"

  # TODO: encrypt the PASSPRASE with the root public key, save it to USB for recovery.
  # TODO: if tpm present, save it to TPM
}


# Add a key to the LUKS partition. This is a recovery key, not the main key - allows owner to open the disk 
# without TPM.
luks_add_key() {
  local disk_dev=$1

  echo -n $KEY > /run/key 
  cryptsetup luksAddKey $disk_dev /run/key
  rm /run/key
}

luks_add_pass() {
  local disk_dev=$1
  local key_file=$2

  cat $SECRETS/passphrase | cryptsetup luksAddKey $disk_dev
}

genpass() {
  cat /dev/urandom | \
     tr -dc a-zA-Z0-9 | \
     head -c14; echo
}

init_pass() {
  #export KEY=$(openssl rand -base64 32)
  export KEY=$(genpass)
  mkdir -p $SECRETS
  echo -n "${KEY}" > $SECRETS/passphrase
  if [ -f /boot/root.pem ]; then
    echo -n "${KEY}" | openssl pkeyutl -encrypt \
         -pubin -inkey /boot/root.pem \
         -pkeyopt rsa_padding_mode:oaep \
         -pkeyopt rsa_oaep_md:sha256 \
         -out /boot/efi/DISK_RECOVERY_KEY
  fi
  echo $KEY
}

recover_key() {
  local ENCRYPTED_PASSPHRASE_FILE=$1
  PRIVATE_KEY=$HOME/.ssh/id_ecdsa

  KEY=$(openssl pkeyutl -decrypt \
     -inkey $PRIVATE_KEY -in $ENCRYPTED_PASSPHRASE_FILE \
     -pkeyopt rsa_padding_mode:oaep -pkeyopt rsa_oaep_md:sha256)
}

efidump() {
  mount  -t efivarfs efivarfs /sys/firmware/efi/efivars

}

gen_pass() {
   cat /dev/urandom | tr -dc a-zA-Z0-9 | head -c14; echo
}

HANDLE=${HANDLE:-0x81000001}

get_pass() {
    KEY=$(tpm2_unseal -c ${HANDLE} -p pcr:sha256:7)
    echo ${KEY}
}

get_pass8() {
    KEY=$(tpm2_unseal -c 0x81000001 -p pcr:sha256:8)
    echo ${KEY}
}

set_pass() { 
  mkdir -p /initos/tpm
  cd /initos/tpm
  # Can be called multiple times, same result
  tpm2_createpolicy --policy-pcr -l sha256:7 -L policy.digest

  echo ${KEY} | tpm2_create -u key.pub -r key.priv -C 0x81000000 -L policy.digest -i -

  tpm2_evictcontrol -c ${HANDLE}
  tpm2_load -C 0x81000000 -u key.pub -r key.priv -c key.ctx -n key.name
  tpm2_evictcontrol -c key.ctx
}

#PRIMARY=0x81800000
#TPM_KIND="-C p"
#HANDLE=0x81800001
TPM_KIND=${TPM_KIND:-}
PRIMARY=${PRIMARY:-0x81000000}
HANDLE=${HANDLE:-0x81000001}

create_primary() {
  # On Chromebook, only -C p works. On another laptop - default only (owner), -C e also works .
  tpm2_createprimary  -c primary.ctx --format=pem --output=primary_pub.pem ${TPM_KIND}
  tpm2_print -t TPMS_CONTEXT primary.ctx # -> Handle: 0x80000000
 
  tpm2_evictcontrol -c ${PRIMARY}
  tpm2_evictcontrol -c primary.ctx -o primary.tr ${TPM_KIND} # persistent-handle: 0x8100...0
  tpm2 print -t ESYS_TR primary.tr
}

list() {
  tpm2_getcap handles-persistent

}

seed() {
  # Disk is read only - but allows adding a new disk, where the writes will go.
  # This can be useful with VMs, sharing a RO base.
  btrfstune -S 1 ${dev}
}

# Check all files and meeta checksums. Reports go to /var/lib/btrfs.
# Docs recommend monthly, from cron. Will use 80% of bw.
scrub() {
  btrfs scrub start -B /x
  btrfs filesystem defrag -v -r -f -t 32M /x
  duperemove -dhr /x
  btrfs balance start -m /x
}

ext4btrfs() {
  local disk=$1

  e2fsck -fvy ${disk}
  btrfs-convert ${disk}

  # btrfs subvolume delete /x/ext2_saved
}

# Run a command in a recovery chroot
recovery() {
  /initos/recovery/usr/bin/arch-chroot /initos/recovery $*
}

# On debian, find the explicitly installed packages
find_installed_deb() {
  dpkg --get-selections | grep -v deinstall | cut -f1
}

get_firmware_info() {
  # Get a list of all loaded modules
  modules=$(lsmod | awk 'NR>1 {print $1}')

  for module in $modules; do
    modinfo_output=$(modinfo $module)

    # Extract firmware information
    firmware_lines=$(echo "$modinfo_output" | grep -i 'firmware:')

    if [ -n "$firmware_lines" ]; then
      echo $module "$firmware_lines"
    fi
  done
}


# save_tpm() {
#   KEY=$1

#   mkdir -p /initos/tpm
#   cd /initos/tpm
  
#   # Can be called multiple times, same result
#   tpm2_createpolicy --policy-pcr -l sha256:7 -L policy.digest

#   #tpm2_getcap handles-persistent | grep -q 0x81800001
#   # if [ $? -ne 0 ]; then
#   # fi

#   # primary.tr or 0x81000000 - the eviccontrol handle
#   #echo ${KEY} | tpm2_create -u key.pub -r key.priv -C primary.tr -L policy.digest -i -
#   echo ${KEY} | tpm2_create -u key.pub -r key.priv -C ${PRIMARY} -L policy.digest -i -

#   # To delete:
#   tpm2_evictcontrol -c ${HANDLE} || true

#   #tpm2_load -C primary.ctx -u key.pub -r key.priv -c key.ctx -n key.name
#   tpm2_load -C ${PRIMARY} -u key.pub -r key.priv -c key.ctx -n key.name
#   tpm2_evictcontrol -c key.ctx ${TPM_KIND}

#   tpm2_print -t TPMS_CONTEXT key.ctx # -> Handle: 0x80000000
#   # persistent-handle: 0x81000001
# }

save_tpm_full() {
  KEY=$1
  mkdir -p /initos/tpm
  cd /initos/tpm
  
  # Can be called multiple times, same result
  tpm2_createpolicy --policy-pcr -l sha256:7 -L policy.digest

  tpm2_getcap handles-persistent | grep -q 0x81800001
  # if [ $? -ne 0 ]; then
  # fi

  # On Chromebook, only -C p works. On another laptop - default only (owner), -C e also works .
  tpm2_createprimary  -c primary.ctx --format=pem --output=primary_pub.pem
  tpm2_print -t TPMS_CONTEXT primary.ctx # -> Handle: 0x80000000
  
  tpm2_evictcontrol -c primary.ctx -o primary.tr # -C p # persistent-handle: 0x8100...0
  tpm2 print -t ESYS_TR primary.tr
  
  # To delete:
  tpm2_evictcontrol -c 0x81000001

  # primary.tr or 0x81000000 - the eviccontrol handle
  #echo ${KEY} | tpm2_create -u key.pub -r key.priv -C primary.tr -L policy.digest -i -
  echo ${KEY} | tpm2_create -u key.pub -r key.priv -C 0x81000000 -L policy.digest -i -

  #tpm2_load -C primary.ctx -u key.pub -r key.priv -c key.ctx -n key.name
  tpm2_load -C 0x81000000 -u key.pub -r key.priv -c key.ctx -n key.name
  tpm2_evictcontrol -c key.ctx
  tpm2_print -t TPMS_CONTEXT key.ctx # -> Handle: 0x80000000
  # persistent-handle: 0x81000001
}

mok() {
  mokutil --sb-state
  mokutil --list-enrolled
  mokutil --pk
  mokutil --kek
  mokutil --db
  # Looks for /var/lib/sbctl/keys/db/db.key
  # sbctl enroll-keys -a -c --yes-this-might-brick-my-machine
}

## Save the LUKS password to TPM
save_tpm_dbg() {
  KEY=$1

    # Key will be disabled if ...

    # Shows the same output every time, probably fine to repeat.
    #tpm2_createpolicy --policy-pcr -l sha256:0,1,2,3 -L policy.digest
    tpm2_createpolicy --policy-pcr -l sha256:8 -L policy.digest

    tpm2_getcap handles-persistent | grep -q 0x81800001
    if [ $? -ne 0 ]; then
      # -C hierarch - e for endorsement, default is owner, also platform
      # -g sha256 - default
      # -G defaults to rsa2048:null:aes128cfb
      # -c file - where to store the 'context' (info about key)
      tpm2_createprimary -C p -c primary.ctx --format=pem --output=primary_pub.pem
      # displays info - including key handle (it seems to be temporary )
      tpm2_print -t TPMS_CONTEXT primary.ctx
      ### Handle: 0x80000000, sequence: 2, 6, 10, etc - size 1914

      # Get a persistent handle
      tpm2_evictcontrol -c primary.ctx -o primary.tr -C p
      # To remove: replace -c primary.ctx with -c 0x81800001
      tpm2 print -t ESYS_TR primary.tr
      # Should hopefully create Handle: 0x81800001
    fi

    # '-C p' worked on some where '-C e' didn't

    # not setting -L makes the key accessible in all cases

    # -i - -- stdin, max 128 bytes
    # -u and -r seem to be used to allow the object to be moved to another TPM
    # -C context (parent object) - not sure how to list
    # -r and -u - where to store the output
    echo ${KEY} | tpm2_create -u key.pub -r key.priv -C 0x81800001 -L policy.digest -i -
    # -C 0x81000000 also works as -C - from handles-persistent
    # -c key.ctx -> also load in the same step, but ChromeOS TPM doesn't support it
    # without -i creates an RSA public key

    tpm2_evictcontrol -C p -c 0x81800002 | true
    # -c - the out file for the context for the key
    # tpm2_create generates the 'export' files.
    tpm2_load -C 0x81800001 -u key.pub -r key.priv -c key.ctx -n key.name

    # -C p - platform (only one working on my chromebook)
    # -c ctx - the key handle or ctx file
    #
    tpm2_evictcontrol -C p -c key.ctx
    # To delete -C p -c ID

     # -> returns a persistent handle (0x81800000) for 'p'

    # Show the list of handles
    tpm2_getcap handles-persistent

}

bootefi() {
  local dev=${1:-/dev/sda}

  mount -t efivarfs none /sys/firmware/efi/efivars

  efibootmgr --disk $dev --part 1 --create --label 'Initos' --load /EFI/boot/InitOS.efi --verbose

}

efibackup() {
  for i in PK KEK db dbx; do efi-readvar -v $i -o $i.esl; done

  # Installing keys:
  # db.auth,  KEK.auth and PK.auth added to bios from USB disk

  # Alternative:
  # apk update
  # apk add sbctl
  # sbctl create-keys
  # sbctl sign /boot/efi/Alpine/linux-lts.efi
  # sbctl enroll-keys -m
}


prepare_usb() {
  local disk_dev=${1:-/dev/sda}

  wipe_disk $disk_dev

  mount ${disk_dev}3 /mnt/usb/root
  mount ${disk_dev}1 /mnt/usb/efi

  cd /mnt/usb/root
  btrfs subvolume create recovery
}



$*
