#!/bin/sh

source /sbin/initos

# Separate script for setting up server machines with TPM2
# All servers should have TPM2 in order to start automatically.
# Without TPM2 - it is possible to start in a locked mode and 
# connect to a control plane for further instructions.
#
# In case of problems (failure to unlock, can't ssh):
# -disable secure mode (may require BIOS password)
# -boot from a USB image if disk is completely gone.
# 


# Main entry point - called by the init script
initos_init() {  
  logi "Starting INITOS TPM2 $(uname -r)"

  # Additional drivers with the real firmware and modules mounted. 
  load_drivers

  # LUKS mounted on /x, secure mode.
  open_luks
        

  # At this point we may have a tpm and may be able to mount
  # encrypted disk.
  # If insecure - the TPM should NOT have the key
  # Without TPM2 - will ask for a password - if it can open the
  # disk - ok, otherwise panic
  mount_btrfs_raw /dev/mapper/c /x
  if [ $? -eq 0 ]; then
      logi "BTRFS mounted"
  else
      lfatal "Failed to mount btrfs"
  fi

  start_os
}

# unlock the encrypted disk using the TPM. 'c' mapper will be used.

unlock_tpm() {
  local part=$1

  # Arch recommends: 1,2,5,7 ( firmware, firmware options, GPT layout, secure
  #  boot status)
  #PCRS="0,1,7"
  # 2 = pluggable executable code
  # 3 = pluggable firmware data
  # 4 = boot manager code
  # 5 = boot manager data, include GPT partitions
  # 6 = resume events
  # 7 = secure boot status, certificates -> This is what 
  #  we want, gpt layout is not relevant, firmware can be
  #  upgraded.

  # The setup script makes sure this handle is set - we may try multiple handles or
  # list nv persistent and try all.

  handle=0x81000001

  if [ -f /boot/efi/initos/tpm_handle ]; then
    handle=$(cat /boot/efi/initos/tpm_handle)
  fi

  PASSPHRASE=$(tpm2_unseal -c ${handle} -p pcr:sha256:7 2>/dev/null)
  
  # if [ -z $PASSPHRASE ]; then 
  #   logi "Handle $handle PCR7 failed, try PCR8" 
  #   PASSPHRASE=$(tpm2_unseal -c ${handle} -p pcr:sha256:8 2>/dev/null)
  # fi 
  # if [ -z $PASSPHRASE ]; then 
  #   logi "Handle $handle failed PCR8 try 8100..2 PCR7" 
  #   handle=0x81000002
  #   PASSPHRASE=$(tpm2_unseal -c ${handle} -p pcr:sha256:7 2>/dev/null)
  # fi 
  if [ -z $PASSPHRASE ]; then 
    logi "Handle $handle:8 failed, try 81800001" 
    handle=0x81800001
    PASSPHRASE=$(tpm2_unseal -c 0x81800001 -p pcr:sha256:7 2>/dev/null)
  fi 
  
  if [ -z $PASSPHRASE ]; then
    echo "Failed to unlock TPM, fallback to recovery" 
    return
  fi
  export PASSPHRASE

  # Try all other handles
  HANDLES=$(tpm2_getcap handles-persistent)
  logi "Persistent handles $HANDLES" 
  


  if [ -z "$part" ]; then
    parts=$(blkid | grep 'TYPE="crypto_LUKS"' | cut -d: -f1 )
    echo "$parts" | while read -r part; do 
      echo -n "$PASSPHRASE" | cryptsetup open $part c -
      if [ $? -eq 0 ]; then
        logi "Opened $part"
        return 0
      fi
    done
  else
    echo -n "$PASSPHRASE" | cryptsetup open $part c -
  fi

}


# open LUKS using TPM2.
# TODO: attempt to open all LUKS devices (multiple NVMEs)
# Mointing the /x and rootfs after, btrfs may span multiple 
# disks.
open_luks() {
  local crypted=$1
  
  echo "Found LUKS device: ${cryptd}"
  
  unlock_tpm $cryptd
  if [ $? -eq 0 ]; then
    logi "TPM unlocked ${cryptd}"
    return 0
  fi

  return 1
}

# If running as PID=1 (from initrd): run initos_init or
# a different function (like vm_init)
if [ "$$" = "1" ]; then
  if [ -z ${1+x} ] ; then
    initos_init
  else 
    # Run one of the functions
    "$@"
  fi
else
  "$@"
fi
