#!/bin/sh

source /sbin/initos

# Initialization in 'secure' (signed) mode with manual unlock.
# 
# User must enter a password to unlock the LUKS encryption - laptops 
# or servers lacking TMP2. 
# 
# It is likely more secure than standalone servers with TPM2 - but can't 
# do unattended boot.

# Main entry point - called by the init script
initos_init() {  
  logi "Starting INITOS manual unlock $(uname -r)"
  
  # Additional drivers with the real firmware and modules mounted. 
  # Wil the drivers are loaded/settiling, asks for a key - set as MODE - which determines how to load persistent disk.
  load_drivers

  for i in 1 2 3; do
    echo
    echo -n "Enter the disk (LUKS) password (attempt $i of 3): "
    read -s KEY

    open_disks "$KEY"
    
    if [ -e /dev/mapper/luks-1 ]; then
      break
    fi

    echo
    echo "Failed to unlock the disk. Please try again."
  done
  
  mount_btrfs_raw /dev/mapper/luks-1 /x
  if [ $? -eq 0 ]; then
      logi "BTRFS mounted"
  else
      lfatal "Failed to mount btrfs"
  fi

  start_os
  #start_ui

  ln -s /etc/init.d/agetty /etc/init.d/agetty.tty1
  /etc/init.d/agetty.tty1 start

  exec tini -s sleep -- infinity 

}

initos_init
