#!/bin/sh

# Setup a VM or container.
# - starts with an OCI image or already expanded rootfs
# - generate startup scripts


fix() {
    setcap cap_net_admin+ep /opt/virt/cloud-hypervisor
}

from() {
    local img=$1

    mkdir -p /x/vol/${POD}

}

vm() {
    cd /x/vol/${POD}
    
}

# mkdisk will create (or overrite) a BTRFS image and pre-populate it with a rootfs.
mkdisk() {
  local img=$1

  mkdir -p ${IMGDIR}
  truncate -s ${vm_disk} ${IMGDIR}/${VM}.img
  # Same as - but simpler/faster than
  # qemu-img create -f raw ${WORK}/disk.img 10G

  # Can be mounted using:
  #dev=$(losetup -f ${WORK}/disk.img --show)

  mkdir -p ${WORK}/rootfs

  mkfs.btrfs ${IMGDIR}/${VM}.img --rootdir ${WORK}/rootfs
  #parted $dev mklabel gpt

  # --shrink will keep the image at the required size - can be used for a base image.
}

