#!/bin/sh

# Build script for a debian rootfs.
# Kernel, Nvidia modules and basic utils.

set -x
set -e

# Destination dir for the efi partition artifacts.
# May include additional files to bake into images.
# Signing the images also requires a volume holding the signing keys
# and configs.
WORK=${WORK:-/data}

# Save the kernel and modules on /data, to be used by the 'sign' image and
# to build the initrd.
# Dockerfile is bind-mounting from the kernel stage - with buildah it is faster
# to copy (at least on btrfs, COW) - it can't mount from a container and creating
# an image involves tar, so no longer COW.
#
# The other choice is to have a large 'sign' image that bundles the kernel
# and modules and is updated with every kernel release. 
# Since one way or another we need /data and /config for signing, we may 
# as well use a separate step of creating the boot/ and lib/modules which
# don't change except on new kernel releases.
save_boot() {
  mkdir -p /data/lib /data/boot
  cp -a /boot/* /data/boot
  cp -a /lib/modules /data/lib
  cp -a /lib/firmware /data/lib
}


# Creat a sqfs under $1 with the name $2, containing all files in this 
# container. 
#
# Another way is to export (pull and export or using crane) and create 
# the sqfs externally.
sqfs() {
  local DIR=${1:-/data/efi/initos}
  local name=${2:-initos}

  # -one-file-system also works on the host - but not so well in a container.

  # buildah unshare -m A=debui -- \
  #  sh -c 'tar -cf - -C ${A} .' | \
  #   sqfstar ${WORK}/vimg/virt.sqfs -e .dockerenv

  #alpine_clear

  # Excluding boot from the sqfs (kernel remains on the image and is used to build
  # the EFI, but no need to add a copy)
  # However the cloud kernel is needed for VM

  mkdir -p ${DIR}
  rm -f ${DIR}/${name}.*

  cd /

  # Doesn't include /boot files (kernel is separate)
  # Includes both normal and cloud modules
  mksquashfs . ${DIR}/${name}.sqfs \
     -regex \
     -e "x/.*" \
     -e "etc/uefi-keys" \
     -e ".dockerenv" \
     -e "data/.*" \
     -e "proc/.*" \
     -e "sys/.*" \
     -e "run/.*" \
     -e "tmp/.*" \
     -e "var/cache/apt/.*" \
     -e "etc/apk/cache.*"
    
  # Not excluding boot, lib - work and ws are no longer mounted (old versions)

  echo "Created ${DIR}/${name}.sqfs"
}


export DEBIAN_FRONTEND=noninteractive
APTINSTALL="apt install --assume-yes --no-install-recommends "


deb_rootfs() {
  $APTINSTALL tpm2-tools fdisk \
    gdisk \
    wpasupplicant  wireless-tools iw efibootmgr squashfs-tools \
    cryptsetup pciutils
}


debian_rootfs_base() {
  add_deb_kernel
  
  add_deb_core
}

add_deb_core() {
  $APTINSTALL ca-certificates curl gpg  

  $APTINSTALL   \
     tini  bsdutils dosfstools  \
     hdparm file findutils fuse3 btrfs-progs lsof \
    \
    rsync ifupdown ifupdown-extra \
     bridge-utils net-tools tcpdump iptables iproute2  \
    nftables iperf3 openssh-server  \
    \
   pciutils squashfs-tools 
}

# Adds Kernel, firmware
# Builds the initrd images for intel/amd uCode.
add_deb_kernel() {
  echo deb http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware >> /etc/apt/sources.list

  apt update
  export INITRD=No
  $APTINSTALL \
   linux-image-amd64 firmware-misc-nonfree \
     firmware-linux-free \
       firmware-realtek \
       firmware-iwlwifi firmware-atheros \
       amd64-microcode intel-microcode

  TMPDIR=/tmp/initrd
  rm -rf $TMPDIR
  mkdir $TMPDIR

  cd $TMPDIR
  mkdir -p kernel/x86/microcode

  if [ -d /lib/firmware/amd-ucode ]; then
    cat /lib/firmware/amd-ucode/microcode_amd*.bin > kernel/x86/microcode/AuthenticAMD.bin
  fi
  find . | cpio -o -H newc >/boot/amd-ucode.img
  
  rm -rf kernel
  mkdir -p kernel/x86/microcode
  if [ -d /lib/firmware/intel-ucode ]; then
   cat /lib/firmware/intel-ucode/* > kernel/x86/microcode/GenuineIntel.bin
  fi

  find . | cpio -o -H newc >/boot/intel-ucode.img

  ver=$(ls /lib/modules |grep -v cloud)
  echo -n ${ver} > /boot/version

  # No longer doing this - separate builder/image for VMs. 
  # Also install the cloud kernel - upgrade them at the same cadence, and
  # will be used to run the real root as a VMs for more security.
  # Images grows from 795 -> 909 M, Initos image from 568-> 634
  # $APTINSTALL \
  #    linux-image-cloud-amd64
  # ver=$(ls /lib/modules |grep cloud)
  # echo -n ${ver} > /boot/cloud-version

  # Can't stop the creation - but not used. Just need the kernel and modules.
  rm -rf /boot/initrd.img* /tpm/* /tmp/* || true
}

"$@"
