name: InitosBuild
on:
  push: {}
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build-docker:
    name: Build-in-docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: sidecar+kernel image
        uses: docker/build-push-action@v6
        with:
          push: true
          target: sidecar
          tags: ghcr.io/costinm/initos/initos-sidecar:latest

      - name: Unsigned EFI boot image
        uses: docker/build-push-action@v6
        with:
          push: true
          target: efi
          tags: ghcr.io/costinm/initos/initos-efi:latest

#      - name: Upload EFI image
#        uses: actions/upload-artifact@v2
#        with:
#          name: efi
#          path: efi

