name: InitosBuild
on:
  push: {}
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build-docker:
    name: Build-in-docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Does not use the checked out files - but the git directly
      - name: push kernel
        uses: docker/build-push-action@v6
        with:
          push: true
          target: kernel
          tags: ghcr.io/costinm/initos/initos-rootfs:latest
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: docker.pkg.github.com
#          repository: costinm/ugate/ugate/initos
          #tag_with_ref: true
      - name: push sidecar
        uses: docker/build-push-action@v6
        with:
          push: true
          target: sidecar
          tags: ghcr.io/costinm/initos/initos-sidecar:latest
      # - name: push builder
      #   uses: docker/build-push-action@v6
      #   with:
      #     push: true
      #     target: builder
      #     tags: ghcr.io/costinm/initos/initos-builder:latest
  
#      - name: Upload EFI image
#        uses: actions/upload-artifact@v2
#        with:
#          name: efi
#          path: efi

