name: Go
on: [push]
env:
  GO111MODULE: on

jobs:
  build-docker:
    name: Build-in-docker
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: push recovery
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/costinm/ugate/initios-recovery:latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
#          registry: docker.pkg.github.com
#          repository: costinm/ugate/ugate/initos
          #tag_with_ref: true

#      - name: Upload EFI image
#        uses: actions/upload-artifact@v2
#        with:
#          name: efi
#          path: efi

